from pathlib import Path
import json,html,re
import diagrams as d
from story import S
ROOT=Path(__file__).resolve().parents[1]
def e(s):return html.escape(s,quote=True)
# Use the actual lecture resource corresponding to the claim.
for s in S:
 if s['id'] in ('fit','tree-check'):s['source']='https://nipunbatra.github.io/ml-teaching/supervised/slides/bias-variance.pdf'
 if s['id']=='cv':s['source']='https://nipunbatra.github.io/ml-teaching/supervised/slides/cross-validation.pdf'
 if s['id'] in ('bagging','ensembles'):s['source']='https://nipunbatra.github.io/ml-teaching/supervised/slides/ensemble.pdf'
 if s['id'] in ('gradient','step-size','batches'):s['source']='https://nipunbatra.github.io/ml-teaching/optimization/slides/gradient-descent.pdf'
 if s['id'].startswith('ridge'):s['source']='https://nipunbatra.github.io/ml-teaching/supervised/slides/ridge-regression.pdf'
parts=[];guide=['# EM619 final recap · 2 October 2026','','49 frames · 55 minutes, including student questions.','', '## Presenting','','Open `index.html?present`. Arrow keys / Space: move; P: reading/presentation; O: overview; Q: question; A: answer; S: speaker notes. The HTML works offline. On phones it opens in reading mode; wide diagrams scroll horizontally. The PDF includes all 49 frames.','', '## Scope and pacing','','Based on the latest dated course record and the instructor’s corrections: 23 Sep MLP continued; 26 Sep next-token prediction; 30 Sep autograd; 2 Oct final recap. Original class recordings and notebooks remain on the schedule. No SVM, CNN, clustering or transformer unit is introduced.','', '| Minutes | Topic |','|---|---|','| 0–7 | Foundations and metrics |','| 7–16 | Trees, cross-validation, ensembles |','| 16–28 | Regression, gradient descent, ridge |','| 28–33 | Logistic regression |','| 33–39 | MLPs |','| 39–44 | Next-character prediction |','| 44–51 | Autograd |','| 51–55 | Synthesis and exit questions |','', 'For 50 minutes, shorten the pauses on geometry, ensemble comparison and parameter counting. For 60 minutes, extend the final diagnosis and student explanations. Do not play all linked videos during the recap.','', '## Teaching conventions','','Numerical examples and curves are illustrative, not experimental results. The names architecture follows the basic notebook (context 5, embedding width 4, hidden width 64, sine activation); the vocabulary size is data-dependent. The XOR example uses ReLU for simple arithmetic. The ridge objective uses MSE plus λ‖w‖² with no intercept penalty.','', '## Frames, questions and notes','']
clock=0
for i,s in enumerate(S):
 demo=''
 if s.get('demo')=='gd':demo='<div class="demo" aria-label="Learning-rate examples">'+''.join(f'<button data-rate="{rate}" aria-pressed="{str(rate=="0.1").lower()}">η = {rate}</button>' for rate in ['0.1','0.8','1.1'])+'</div>'
 if s.get('demo')=='generation':demo='<div class="demo"><button id="gen-reset">Reset trace</button><button id="gen-next">Next character</button><span id="gen-state" aria-live="polite"></span></div>'
 visual=s['visual'].replace('role="img"',f'role="img" aria-label="{e(s["title"])}"')
 (ROOT/'figures'/f'{i+1:02}-{s["id"]}.svg').write_text(visual)
 parts.append(f'''<section class="slide {s.get('kind','')}" id="{s['id']}" aria-labelledby="h-{s['id']}"><header><p class="eyebrow">{e(s['section'])}</p><h{'1' if i==0 else '2'} id="h-{s['id']}">{e(s['title'])}</h{'1' if i==0 else '2'}></header><div class="visual">{visual}</div>{demo}<p class="idea">{e(s['idea'])}</p><p class="qbox">{e(s['question'])}</p><div class="reading"><details><summary>Question and answer</summary><p><strong>{e(s['question'])}</strong></p><p>{e(s['answer'])}</p></details><details><summary>Teaching notes · {s['seconds']} seconds</summary><p>{e(s['notes'])}</p><p><a href="{e(s['source'])}">Original class material</a></p></details></div><span class="slide-number">EM 619 · {i+1} / {len(S)}</span></section>''')
 guide +=[f'### {i+1:02} · {s["title"]} ({clock//60:02}:{clock%60:02}, {s["seconds"]} s)','',s['idea'],'',f'**Ask:** {s["question"]}','',f'**Answer:** {s["answer"]}','',s['notes'],'',f'[Original class material]({s["source"]})',''];clock+=s['seconds']
metadata=[{k:v for k,v in s.items() if k!='visual'} for s in S]
safe=lambda obj:json.dumps(obj,ensure_ascii=False).replace('<','\\u003c')
html_doc=f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>EM 619 · Course recap · 2 October 2026</title><meta name="description" content="A 55-minute visual recap of EM619: trees, regression, optimization, logistic regression, MLPs, next-character prediction and autograd."><style>{(ROOT/'src/lecture.css').read_text()}</style></head><body><nav class="toolbar" aria-label="Presentation controls"><span class="brand">EM 619 · Course recap</span><button id="prev" aria-label="Previous slide">←</button><span class="counter" id="counter"></span><button id="next" aria-label="Next slide">→</button><button id="present">Present (P)</button><button id="overview">Overview (O)</button><button id="question">Q</button><button id="answer">A</button><button id="notes">Notes (S)</button></nav><main class="stage">{''.join(parts)}</main><footer>2 October 2026 · Nipun Batra · IIT Gandhinagar<br><a href="https://nipunbatra.github.io/em619-2026/schedule.html">Course schedule and revision resources</a> · <a href="em619-course-recap.pdf">PDF</a> · <a href="TEACHING_GUIDE.md">Teaching guide</a><p>Keyboard: arrows / Space to move, P to present/read, O for overview, Q for question, A for answer, S for notes.</p></footer><dialog id="dialog"><div class="dialog-head"><h2 id="dialog-title"></h2><button id="close">Close</button></div><div id="dialog-body"></div></dialog><script id="slide-data" type="application/json">{safe(metadata)}</script><script id="gd-data" type="application/json">{safe({str(r):d.gd(r) for r in [.1,.8,1.1]})}</script><script>{(ROOT/'src/lecture.js').read_text()}</script></body></html>'''
(ROOT/'index.html').write_text(html_doc)
(ROOT/'TEACHING_GUIDE.md').write_text('\n'.join(guide))
(ROOT/'slide-manifest.json').write_text(json.dumps(metadata,indent=2)+'\n')
print(f'Built {len(S)} slides; {clock/60:g} minutes; {len(html_doc.encode())//1024} KB offline HTML')
